### ISSUE TITLE
All buffers are opened in hex mode

### ISSUE THREAD

**Issue by matt1003** [fidian/hexmode#36]
The command `vim -b [file]` opens the buffer in hex mode, as expected, however all subsequent buffers opened are also opened in hex mode. For example:

`vim -b ~/.bashrc` (bashrc is opened in hex mode, as expected)
`:e ~/.vimrc` (vimrc is also opened in hex mode)

This also occurs when opening QiuckFix/Location buffers.

Note, this does **not** occur when using the `Hexmode` command. For example:

`vim ~/.bashrc` (bashrc is opened in text mode, as expected)
`:Hexmode` (bashrc is converted to hex mode, as expected)
`:e ~/.vimrc` (vimrc is opened in text mode, as expected)

**Comment by fidian** [comment]
I don't think this is actually a problem.

When you use `vim file` and turn on Hexmode, it will change the buffer and sets some variables so that saving would write the file correctly. Editing the second file will wipe out those changes and doesn't load the new file in Hexmode because Hexmode was enabled on a per-file basis.

When using `vim -b file`, this turns on the `&l:binary` flag. When a file is opened, Hexmode looks at the variable and determines that it should open the file with Hexmode enabled. When you use `:e anotherfile` to open a second file, the flag is still enabled and Hexmode will still be triggered. The binary flag changes how files are read and saved as well, so one doesn't really want a plugin to disable the flag after a file is loaded.

I can see how this behavior doesn't match what you expect. With the Hexmode plugin disabled, `vim` operates in an "all or nothing" type of approach, where the `&l:binary` flag usually stays on or stays off between files. I believe the Hexmode plugin should not change this behavior.

I'm closing the issue because this isn't a bug of how the plugin operates. If this explanation doesn't quite satisfy your needs, feel free to reopen this issue.
